### PR TITLE
Remove reference to non-linearity and Boolean

### PR DESCRIPTION
**Pull request by DimmestP**

### CODE REVIEW

**Comment by ewallace** [comment]
I'm going to review these edits and make some other changes to the intro, then kick back to @DimmestP for his review.

**Comment by ewallace** [comment]
I would like @DimmestP to check this then merge.

**Comment by DimmestP** [comment]
Not sure why we should introduce introns and exons in the transcription description. a) we don't refer to them in the paper and b) since we work in S.cer, only in a fraction of genes does transcription progress over introns.

I was taught that if you quote a word, i.e. "parts", then you have to quote it every time you use it. Quoting implies you are using someone else's words and unquoting suggests it's actually your word which is confusing. I think we can drop the quotes entirely.

I like the  idea of contrasting modular assembly and composability. I think the paragraph showing uses of modular assembly is great but I think some elaboration on issues arising due to common assumptions used to explore composability would solidify the intro.

Once we've clarified our issue with current methods to explore composability, I think the intro will set up the  paper very nicely.

**Comment by ewallace** [comment]
You're right, we can do without introns and exons. The previous section said transcription continues "through the coding sequence", which is incomplete due to introns and other noncoding regions. What about "through the body of the transcript" or "rest of the transcrip" of "gene body" or something?

Also I'm happy to drop the quotes on "parts".

**Comment by DimmestP** [comment]
@ewallace to review changes to intro:
Removed intron/exons
Removed quotes
Changed references to composability to try and frame the question clearly

**Comment by ewallace** [comment]
Jamie pointed out that "synthesis" usually refers to chemical synthesis (e.g. of DNA), contrasting with the assembly of synthesised parts. I made that edit.

The introduction is looking very good now so I am merging into master.

**Pull request merged**
