### PR TITLE
Discussion mechanism, resolves #137

### LINKED ISSUE #137: Tighten up discussion "Mechanisms for motif terminator context dependence"
This could flow better and be more consistent about CREs vs motifs (#80). I will take a go through this section.

### PR DESCRIPTION
**Pull request by ewallace**
I have rewritten the chunk of discussion on mechanism to try and improve flow and clarity. Requesting review initially from Sam, later from others.

* C. elegans lin-4 / lin-14 regulation has its own paragraph
* Yeast ASH1 has its own paragraph with some different references
* Ssd1 regulation has its own paragraph, referring to the repressive effect of tSUN4 and tTOS6
* NEEDS ATTENTION: do we want to discuss alternate transcript isoforms? I think this needs either to be taken out, or specific examples added where one CRE changes the isoform and the other is present or not as a result.

We need to add references, @DimmestP could you?

- [Niedner2014](https://doi.org/10.4161/rna.29946)
- [Paquin2007](http://dx.doi.org/10.1016/j.molcel.2007.05.016)
- [Jansen2009](https://dx.doi.org/10.1016%2Fj.cub.2009.10.071)
- [Chartrand1999](http://dx.doi.org/10.1016/S0960-9822(99)80144-4)
- [Gonzalez1999](http://dx.doi.org/10.1016/S0960-9822(99)80145-6 )
- [Cereda2014](https://doi.org/10.1186/gb-2014-15-1-r20)

### CODE REVIEW

**Comment by ewallace** [comment]
Added another timing example, CLB3, and reference [Berchowitz2013](http://genesdev.cshlp.org/content/27/19/2147.short)

**Comment by DimmestP** [comment]
Added References as requested.

Reads very well but I have altered a few sentences:

**Changed**

> Similarly, to establish meiotic chromosome segregation in budding yeast, mRNA encoding cyclin CLB3 is transcribed in stage I of meiosis, then translationally repressed via its 5'UTR by the RNA-binding protein Rim4, which is relieved during stage II of meiosis by phosphorylation of Rim4 [@Berchowitz2013]
> Here, 5'UTR-specified translational control of CLB3 by Rim4 depends on the timing of promoter-specified transcriptional control.

**To**

> Similarly, to establish meiotic chromosome segregation in budding yeast, mRNA encoding cyclin CLB3 is transcribed in stage I of meiosis, but is translationally repressed until stage II of meiosis.
> CLB3 is translationally repressed via its 5'UTR by the RNA-binding protein Rim4.
> During the transition to meiosis II, Rim4 is phosphorylated which inhibits binding to CLB3 and enables CLB3 to be translated [@Berchowitz2013].
> Here, 5'UTR-specified translational control of CLB3 by Rim4 depends on the timing of promoter-specified transcriptional control.

**Changed**

> Spatial regulation by successive CREs is also important, as one CRE can confer localisation followed by another CRE conferring localisation-dependent regulation.

**To**

> Spatial regulation by successive CREs is also important, as one CRE can facilitate transcript localisation whilst other CREs and/or TREs confer localisation-dependent regulation.

The ASH1 example is more about TREs changing function rather than CREs right?

Still to address the alternative polyA effects on CREs

**Comment by ewallace** [comment]
Looks good.

> The ASH1 example is more about TREs changing function rather than CREs right?
It's complicated because there is so much known about ASH1. There is one point that CREs are cooperative and redundant. Then there is another point that the literature argues that one CRE specifies localisation, then a later CRE-specified TRE acts dependent on the localisation. So the second TRE depends on, first,  CRE1 and TRE1 putting the transcript in the right place, second, CRE2 directly binding TRE2.

I am struggling to explain this simply.

**Comment by DimmestP** [comment]
For now I have removed the partial paragraph on Alt PolyA usage and its effect on CREs. This leaves the discussion self contained. I have added an issue to remind us to return to the PolyA paragraph later on.

**Comment by ewallace** [comment]
Sounds good - can we merge this pull request now, then?

**Pull request merged**
