### PR TITLE
Updates summary tables and moves to main text

### LINKED ISSUE #144: Add Pelechano Mean and Read Mean to Terminator Table

### LINKED ISSUE #145: Refine motif/terminator summary tables
Terminator table:
- Non weighted and weighted median 3'UTR length columns
- Two word gene ontology
- Change "Usage" column to one letter summary (explain meaning in caption)
- Move to main text
- Add Caption
- Clearer column name for terminator lengths

Motif Table:
- caption
- move to main text

### PR DESCRIPTION
**Pull request by DimmestP**
Fix #145 
Fix #144

### CODE REVIEW

**Comment by ewallace** [comment]
I love the idea of this, @DimmestP could you please commit the .tsv files and double-check the manuscript compiles (it might need `magrittr` for the pipe)? Then I can review in context.

**Comment by DimmestP** [comment]
Apologies, I have now added the missing tables.

**Comment by ewallace** [comment]
Thanks - I'm still getting
```
Error: '/chimera_project_manuscript/results_chapter/data/terminator_summary_table.csv' does not exist.
```

**Comment by ewallace** [comment]
I made some small edits.

One question: could we add a column of the terminator sizes that we actually used in our experiments? Seems important.

**Comment by DimmestP** [comment]
Added terminator lengths and happy to merge.

**Comment by ewallace** [comment]
I think column title "Construct Terminator Length" not "Inferred Terminator Length".

Is it just me, or should we be worried that the "low-expression" terminators might eb truncated?

**Comment by DimmestP** [comment]
Low expressing terminators definitely could be truncated.

**Pull request merged**
