### PR TITLE
Reverts to abstraction of genes

### PR DESCRIPTION
**Pull request by DimmestP**
My main change was to revert to saying genes are abstracted into CREs. I don't think it's correct to say CREs are abstracted into discrete modules. You can assume CREs are discrete modules but I dont think that is an example of abstraction. The generalisation of genes as a combination of separate sequences with distinct functions is the abstraction.

### CODE REVIEW

**Comment by ewallace** [comment]
Thanks, the focus on genes abstracted into CREs makes sense. I tried to make the main message even simpler.

My main concern is that it sounds like we are saying the coding sequence is a CRE, but I think it would be more usual to say CREs as distinct from coding sequence.

**Comment by DimmestP** [comment]
Should we remove coding sequence from the first sentence then?

**Comment by ewallace** [comment]
What about:
> Genes are commonly abstracted into a coding sequence and cis-regulatory elements (CREs), such as promoter and terminator regions, and short sequence motifs within those.

**Comment by DimmestP** [comment]
:+1:

**Pull request merged**
