### PR TITLE
Nucleic Acids Research formatting

### PR DESCRIPTION
**Pull request by ewallace**
https://academic.oup.com/nar/pages/Ms_Prep_Submission

And let's check the author checklist: https://static.primary.prod.gcms.the-infra.com/static/site/nar/document/Author-checklist-170718.pdf

Including, oh dear, references in number style with no URLs.

### CODE REVIEW

**Comment by DimmestP** [comment]
I have changed the referencing to numerical style. However, I still need to go through every reference and remove any direct referrals to papers, i.e. "replace using the data in [12]" to "using the data in chan et al 2018 [12]".

**Comment by ewallace** [comment]
@DimmestP Is this branch still relevant?

**Comment by ewallace** [comment]
Hi @DimmestP. If we are going to submit to NAR then we still need to format as per NAR requirements. So after resolving #215, let's address this formatting issue.

**Comment by ewallace** [comment]
@DimmestP has resolved this in #205

**Pull request closed without merging**
